const express = require("express");
const router = express.Router();
const { deleteUser, update, registerUser, loginUser, checkToken, checkMail, updatePassWord, changepassword, getuser } = require("../controllers/userController");
const validateToken = require("../middleware/validateTokenHandler");
const validateTokenAdminHandler = require("../middleware/validateTokenAdminHandler");
router.post("/register", registerUser);
router.post("/login", loginUser);
router.get("/checkToken", validateToken, checkToken);
router.post("/checkMail", checkMail);
router.post("/updatePassWord", updatePassWord);
router.post("/changepassword", validateToken, changepassword);
router.get("/getuser", validateToken, getuser);
router.post("/update", validateTokenAdminHandler, update);
router.delete("/delete/:id", validateTokenAdminHandler, deleteUser);
module.exports = router;